# Generated by Django 2.2 on 2020-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='last_update',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
